/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BetaCodeConverter.java
 *
 * Created on Oct 20, 2012, 8:38:33 PM
 */

package greek.gui;

/**
 *
 * @author brian
 */
public class BetaCodeConverter extends javax.swing.JFrame {

    /** Creates new form BetaCodeConverter */
    public BetaCodeConverter() {
	    _converter = new greek.code.BetaCodeBestEffortConverter();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                inputBox = new javax.swing.JTextField();
                convertButton = new javax.swing.JButton();
                outputBox = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Beta Code Converter");

                inputBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                inputBoxActionPerformed(evt);
                        }
                });

                convertButton.setText("Convert");
                convertButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                convertButtonActionPerformed(evt);
                        }
                });

                outputBox.setText("<no input yet>");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outputBox)
                                        .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(inputBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(convertButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputBox)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void inputBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBoxActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_inputBoxActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed

	    String result = _converter.toPrecombinedUnicode(inputBox.getText());
	    if(result == null) result = "<invalid>";
	    this.outputBox.setText(result);

    }//GEN-LAST:event_convertButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BetaCodeConverter().setVisible(true);
            }
        });
    }

	private greek.code.BetaCodeConverter _converter;

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton convertButton;
        private javax.swing.JTextField inputBox;
        private javax.swing.JLabel outputBox;
        // End of variables declaration//GEN-END:variables

}
