/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UncontrVerbConjugator.java
 *
 * Created on Nov 1, 2012, 12:24:50 AM
 */

package greek.gui;

import greek.code.PhonoCode;
import greek.code.Unicode;
import greek.grammar.Mood;
import greek.grammar.Person;
import greek.grammar.Number;
import greek.grammar.Tense;
import greek.grammar.Voice;
import greek.morphology.Morpheme;
import greek.morphology.verb.ThematicContr;
import greek.spelling.Grapheme;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author brian
 */
public class ContrVerbConjugator extends javax.swing.JFrame {

    /** Creates new form UncontrVerbConjugator */
    public ContrVerbConjugator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                inputField = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                conjugateButton = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                jPanel3 = new javax.swing.JPanel();
                firstSingLabel = new javax.swing.JLabel();
                secondSingLabel = new javax.swing.JLabel();
                thirdSingLabel = new javax.swing.JLabel();
                firstPluralLabel = new javax.swing.JLabel();
                secondPluralLabel = new javax.swing.JLabel();
                thirdPluralLabel = new javax.swing.JLabel();
                impvSingLabel = new javax.swing.JLabel();
                impvPluralLabel = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setText("STEM");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                conjugateButton.setText("CONJUGATE");
                conjugateButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                conjugateButtonActionPerformed(evt);
                        }
                });

                jPanel3.setLayout(new java.awt.GridLayout(8, 1));

                firstSingLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(firstSingLabel);

                secondSingLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(secondSingLabel);

                thirdSingLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(thirdSingLabel);

                firstPluralLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(firstPluralLabel);

                secondPluralLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(secondPluralLabel);

                thirdPluralLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(thirdPluralLabel);

                impvSingLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(impvSingLabel);

                impvPluralLabel.setFont(new java.awt.Font("Ubuntu", 0, 36));
                jPanel3.add(impvPluralLabel);

                jScrollPane1.setViewportView(jPanel3);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conjugateButton, javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conjugateButton)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void conjugateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conjugateButtonActionPerformed
	String input = inputField.getText();
	Morpheme stem = PhonoCode.toMorpheme(input);
	if(stem != null) {
		_verb = getLexeme(stem);
		setOutput(firstSingLabel, Mood.INDICATIVE, Person.FIRST, Number.SINGULAR);
		setOutput(secondSingLabel, Mood.INDICATIVE, Person.SECOND, Number.SINGULAR);
		setOutput(thirdSingLabel, Mood.INDICATIVE, Person.THIRD, Number.SINGULAR);
		setOutput(firstPluralLabel, Mood.INDICATIVE, Person.FIRST, Number.PLURAL);
		setOutput(secondPluralLabel, Mood.INDICATIVE, Person.SECOND, Number.PLURAL);
		setOutput(thirdPluralLabel, Mood.INDICATIVE, Person.THIRD, Number.PLURAL);
		setOutput(impvSingLabel, Mood.IMPERATIVE, Person.SECOND, Number.SINGULAR);
		setOutput(impvPluralLabel, Mood.IMPERATIVE, Person.SECOND, Number.PLURAL);
	    }
    }//GEN-LAST:event_conjugateButtonActionPerformed

    private greek.lexeme.Verb getLexeme(Morpheme stem) {
	    return new ThematicContr(stem);
    }

    private void setOutput(JLabel label, Mood m, Person p, Number n) {
	String text = "<invalid input>";
	if(_verb != null) {
		Morpheme morpheme = _verb.getVerbForm(Tense.PRESENT, Voice.ACTIVE, m, p, n).getMorpheme();
		if(morpheme != null) {
			List<Grapheme> graphemes = morpheme.getGraphemes();
			if(graphemes != null) {
				String s = Unicode.toPrecombinedUnicode(graphemes);
				if(s != null) text = s;
				else text = "<Unicode could not be formed>";
			}
			else text = "<grapheme could not be formed>";
		}
		else text = "<morpheme could not be formed>";
	}
	else text = "<verb could not be formed>";
	label.setText(text);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContrVerbConjugator().setVisible(true);
            }
        });
    }

	private greek.lexeme.Verb _verb;

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton conjugateButton;
        private javax.swing.JLabel firstPluralLabel;
        private javax.swing.JLabel firstSingLabel;
        private javax.swing.JLabel impvPluralLabel;
        private javax.swing.JLabel impvSingLabel;
        private javax.swing.JTextField inputField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel secondPluralLabel;
        private javax.swing.JLabel secondSingLabel;
        private javax.swing.JLabel thirdPluralLabel;
        private javax.swing.JLabel thirdSingLabel;
        // End of variables declaration//GEN-END:variables

}
