/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UncontrVerbConjugator.java
 *
 * Created on Nov 1, 2012, 12:24:50 AM
 */

package greek.gui;

import greek.code.PhonoCode;
import greek.code.Unicode;
import greek.grammar.Mood;
import greek.grammar.Person;
import greek.grammar.Number;
import greek.grammar.Tense;
import greek.grammar.Voice;
import greek.morphology.Morpheme;
import greek.morphology.verb.ThematicUncontr;
import greek.spelling.Grapheme;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author brian
 */
public class UncontrVerbConjugator extends javax.swing.JFrame {

    /** Creates new form UncontrVerbConjugator */
    public UncontrVerbConjugator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                firstSingLabel = new javax.swing.JLabel();
                firstPluralLabel = new javax.swing.JLabel();
                secondSingLabel = new javax.swing.JLabel();
                secondPluralLabel = new javax.swing.JLabel();
                thirdSingLabel = new javax.swing.JLabel();
                thirdPluralLabel = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                inputField = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                conjugateButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setLayout(new java.awt.GridLayout(3, 2));

                firstSingLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
                jPanel1.add(firstSingLabel);

                firstPluralLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
                jPanel1.add(firstPluralLabel);

                secondSingLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
                jPanel1.add(secondSingLabel);

                secondPluralLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
                jPanel1.add(secondPluralLabel);

                thirdSingLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
                jPanel1.add(thirdSingLabel);

                thirdPluralLabel.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
                jPanel1.add(thirdPluralLabel);

                jLabel1.setText("Stem:");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                conjugateButton.setText("Conjugate");
                conjugateButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                conjugateButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(conjugateButton)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conjugateButton)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void conjugateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conjugateButtonActionPerformed
	String input = inputField.getText();
	Morpheme stem = PhonoCode.toMorpheme(input);
	_verb = stem == null ? null : new ThematicUncontr(stem);
	setOutput(firstSingLabel, Person.FIRST, Number.SINGULAR);
	setOutput(secondSingLabel, Person.SECOND, Number.SINGULAR);
	setOutput(thirdSingLabel, Person.THIRD, Number.SINGULAR);
	setOutput(firstPluralLabel, Person.FIRST, Number.PLURAL);
	setOutput(secondPluralLabel, Person.SECOND, Number.PLURAL);
	setOutput(thirdPluralLabel, Person.THIRD, Number.PLURAL);
    }//GEN-LAST:event_conjugateButtonActionPerformed

    private void setOutput(JLabel label, Person p, Number n) {
	String text = "<invalid input>";
	if(_verb != null) {
		Morpheme m = _verb.getVerbForm(Tense.PRESENT, Voice.ACTIVE, Mood.INDICATIVE, p, n).getMorpheme();
		if(m != null) {
			List<Grapheme> graphemes = m.getGraphemes();
			if(graphemes != null) {
				String s = Unicode.toPrecombinedUnicode(graphemes);
				if(s != null) text = s;
				else text = "<Unicode could not be formed>";
			}
			else text = "<grapheme could not be formed>";
		}
		else text = "<morpheme could not be formed>";
	}
	else text = "<verb could not be formed>";
	label.setText(text);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UncontrVerbConjugator().setVisible(true);
            }
        });
    }

	private ThematicUncontr _verb;

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton conjugateButton;
        private javax.swing.JLabel firstPluralLabel;
        private javax.swing.JLabel firstSingLabel;
        private javax.swing.JTextField inputField;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel secondPluralLabel;
        private javax.swing.JLabel secondSingLabel;
        private javax.swing.JLabel thirdPluralLabel;
        private javax.swing.JLabel thirdSingLabel;
        // End of variables declaration//GEN-END:variables

}
