package greek.gui;

import greek.util.Joiner;
import greek.code.BetaCode;
import greek.code.BetaCodeBestEffortConverter;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.DefaultListModel;
import java.awt.FileDialog;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class VocabFileViewer extends javax.swing.JFrame {

    /** Creates new form VocabFileViewer */
    public VocabFileViewer() {
	_listModel = new DefaultListModel<String>();
	//_pattern = Pattern.compile("(.*),\\s*(\'.*\',\\s*)*(\'.*\')");
	_pattern = Pattern.compile("(.*?)(?: [(](.*)-[)])?, (([A-Za-z]+[.] )?['].*['])( ([A-Za-z]+[.]) (.*))?");
	_converter = new BetaCodeBestEffortConverter();
        initComponents();
    }

    static {
	String temp = "";
	for(greek.code.BetaCode c : greek.code.BetaCode.values()) {
		temp += c.getCharacter();
	}
	bc = temp;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                mainList = new javax.swing.JList<String>();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Greek Vocabulary Viewer");

                mainList.setModel(_listModel);
                jScrollPane1.setViewportView(mainList);

                jButton1.setText("Load File");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jButton1)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

	FileDialog d = new FileDialog(this);
	d.setDirectory("/home/brian/Dropbox/dusell/programming/greek/vocab");
	d.setAlwaysOnTop(true);
	d.setMode(FileDialog.LOAD);
	d.setVisible(true);
	String filename = d.getFile();
	if(filename != null) {
		_listModel.clear();
		BufferedReader r;
		try {
			r = new BufferedReader(new FileReader(new File(d.getDirectory(), d.getFile())));
			String line, output;
			while((line = r.readLine()) != null) {
				Matcher m = _pattern.matcher(line);
				output = "<no match>";
				if(m.find()) {
					greek.util.Joiner j = new Joiner("");
					if(m.group(1) != null) j.add(_converter.toPrecombinedUnicode(m.group(1)));
					if(m.group(2) != null) j.add(" (" + BetaCode.betaCodeToPrecombinedUnicode(m.group(2)) + "-)");
					if(m.group(3) != null) j.add(", " + m.group(3));
					if(m.group(6) != null) j.add(", " + m.group(6));
					if(m.group(7) != null) j.add(" " + _converter.toPrecombinedUnicode(m.group(7)));
					output = j.result();
				}
				else {
					output = _converter.toPrecombinedUnicode(line);
				}
				_listModel.addElement(output);
			}
			r.close();
		}
		catch(java.io.FileNotFoundException e) {
			System.out.println("unable to open file " + filename);
		}
		catch(java.io.IOException e) {
			
		}
		catch(java.util.regex.PatternSyntaxException e) {
			System.out.println(e);
		}
	}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VocabFileViewer().setVisible(true);
            }
        });
    }

	private static final String bc; // beta code character class

	private javax.swing.DefaultListModel<String> _listModel;
	private java.util.regex.Pattern _pattern;
	private greek.code.BetaCodeConverter _converter;

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JList<String> mainList;
        // End of variables declaration//GEN-END:variables

}
